// ESLint Flat Config (ESLint v9+)
// eslint.config.js

import js from '@eslint/js';
import globals from 'globals';

export default [
  // Ignore patterns
  {
    ignores: [
      'node_modules/**',
      '.claude/mcp-servers/**/node_modules/**',
      'dist/**',
      'coverage/**',
      '*.log',
      '.claude/logs/**',
      '.claude/checkpoints/**',
      'vercel.json',
      '.gitleaks.toml',
      '.gitignore'
    ]
  },

  // Base recommended config
  js.configs.recommended,

  // JavaScript files configuration
  {
    files: ['**/*.js', '**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.es2022,
        document: 'readonly',
        window: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        requestAnimationFrame: 'readonly',
        IntersectionObserver: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        HTMLElement: 'readonly',
        HTMLDocument: 'readonly',
        Node: 'readonly',
        Element: 'readonly',
        NodeList: 'readonly',
        Array: 'readonly',
        Object: 'readonly',
        Promise: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        JSON: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        RegExp: 'readonly',
        Error: 'readonly',
        TypeError: 'readonly',
        RangeError: 'readonly',
        SyntaxError: 'readonly'
      }
    },
    rules: {
      // Possible Errors
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-undef': 'off', // Using globals instead
      'no-constant-binary-expression': 'warn',
      'no-cond-assign': 'warn',
      'no-constant-condition': 'warn',
      'no-duplicate-case': 'warn',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-extra-boolean-cast': 'warn',
      'no-extra-parens': 'off',
      'no-irregular-whitespace': 'warn',
      'no-obj-calls': 'warn',
      'no-prototype-builtins': 'warn',
      'no-regex-spaces': 'warn',
      'no-sparse-arrays': 'warn',
      'no-template-curly-in-string': 'warn',
      'no-unreachable': 'warn',
      'no-unsafe-negation': 'warn',
      'use-isnan': 'warn',
      'valid-typeof': 'warn',

      // Best Practices
      'accessor-pairs': 'warn',
      'array-callback-return': 'warn',
      'block-scoped-var': 'warn',
      'complexity': ['warn', { max: 15 }],
      'curly': ['warn', 'multi-line'],
      'default-case': 'warn',
      'default-case-last': 'warn',
      'default-param-last': 'warn',
      'dot-notation': ['warn', { allowKeywords: true }],
      'eqeqeq': ['warn', 'smart'],
      'grouped-accessor-pairs': 'warn',
      'guard-for-in': 'warn',
      'max-classes-per-file': ['warn', { max: 1 }],
      'no-alert': 'warn',
      'no-caller': 'warn',
      'no-case-declarations': 'warn',
      'no-constructor-return': 'warn',
      'no-div-regex': 'warn',
      'no-else-return': 'warn',
      'no-empty-function': ['warn', { allow: ['arrowFunctions', 'functions', 'methods'] }],
      'no-empty-pattern': 'warn',
      'no-eq-null': 'warn',
      'no-eval': 'warn',
      'no-extend-native': 'warn',
      'no-extra-bind': 'warn',
      'no-extra-label': 'warn',
      'no-implicit-coercion': 'warn',
      'no-implicit-globals': 'warn',
      'no-implied-eval': 'warn',
      'no-invalid-this': 'warn',
      'no-iterator': 'warn',
      'no-labels': 'warn',
      'no-lone-blocks': 'warn',
      'no-loop-func': 'warn',
      'no-multi-assign': 'warn',
      'no-multi-str': 'warn',
      'no-new': 'warn',
      'no-new-func': 'warn',
      'no-new-wrappers': 'warn',
      'no-octal': 'warn',
      'no-octal-escape': 'warn',
      'no-param-reassign': ['warn', { props: true }],
      'no-proto': 'warn',
      'no-redeclare': ['warn', { builtinGlobals: false }],
      'no-restricted-properties': [
        'warn',
        {
          object: 'arguments',
          property: 'callee',
          message: 'arguments.callee is deprecated'
        },
        {
          object: 'global',
          property: 'isFinite',
          message: 'Use Number.isFinite instead'
        },
        {
          object: 'global',
          property: 'isNaN',
          message: 'Use Number.isNaN instead'
        }
      ],
      'no-return-assign': ['warn', 'except-parens'],
      'no-return-await': 'warn',
      'no-script-url': 'warn',
      'no-self-assign': ['warn', { props: true }],
      'no-self-compare': 'warn',
      'no-sequences': 'warn',
      'no-throw-literal': 'warn',
      'no-unmodified-loop-condition': 'warn',
      'no-unused-expressions': ['warn', { allowShortCircuit: true, allowTernary: true }],
      'no-unused-labels': 'warn',
      'no-useless-call': 'warn',
      'no-useless-catch': 'warn',
      'no-useless-concat': 'warn',
      'no-useless-return': 'warn',
      'no-void': 'warn',
      'no-warning-comments': ['warn', { terms: ['todo', 'fixme', 'xxx'], location: 'anywhere' }],
      'prefer-named-capture-group': 'warn',
      'prefer-promise-reject-errors': ['warn', { allowEmptyReject: true }],
      'prefer-regex-literals': ['warn', { disallowRedundantWrapping: true }],
      'radix': 'warn',
      'require-await': 'warn',
      'require-unicode-regexp': 'warn',
      'vars-on-top': 'warn',
      'yoda': 'warn',

      // Variables
      'init-declarations': 'off',
      'no-catch-shadow': 'off',
      'no-delete-var': 'warn',
      'no-label-var': 'warn',
      'no-restricted-globals': ['warn', 'isFinite', 'isNaN'],
      'no-shadow': 'off',
      'no-shadow-restricted-names': 'warn',
      'no-undef': 'off',
      'no-undef-init': 'warn',
      'no-undefined': 'off',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],

      // Style
      'array-bracket-spacing': ['warn', 'never'],
      'block-spacing': ['warn', 'always'],
      'brace-style': ['warn', '1tbs', { allowSingleLine: true }],
      'comma-dangle': ['warn', 'always-multiline'],
      'comma-spacing': ['warn', { before: false, after: true }],
      'comma-style': ['warn', 'last'],
      'computed-property-spacing': ['warn', 'never'],
      'dot-location': ['warn', 'property'],
      'eol-last': ['warn', 'always'],
      'func-call-spacing': ['warn', 'never'],
      'function-call-argument-newline': ['warn', 'consistent'],
      'function-paren-newline': ['warn', 'consistent'],
      'generator-star-spacing': ['warn', 'before'],
      'implicit-arrow-linebreak': ['warn', 'beside'],
      'indent': ['warn', 2, { SwitchCase: 1, VariableDeclarator: 1 }],
      'key-spacing': ['warn', { beforeColon: false, afterColon: true }],
      'keyword-spacing': ['warn', { before: true, after: true }],
      'line-comment-position': ['warn', { position: 'above' }],
      'linebreak-style': ['warn', 'unix'],
      'lines-around-comment': ['warn', { beforeBlockComment: true }],
      'lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: true }],
      'max-depth': ['warn', { max: 4 }],
      'max-len': ['warn', { code: 100, ignoreStrings: true, ignoreTemplateLiterals: true, ignoreRegExpLiterals: true }],
      'max-lines': ['warn', { max: 300, skipBlankLines: true, skipComments: true }],
      'max-lines-per-function': ['warn', { max: 50, skipBlankLines: true, skipComments: true }],
      'max-nested-callbacks': ['warn', { max: 3 }],
      'max-params': ['warn', { max: 4 }],
      'max-statements': ['warn', { max: 20 }],
      'multiline-comment-style': ['warn', 'starred-block'],
      'multiline-ternary': ['warn', 'always-multiline'],
      'new-cap': ['warn', { newIsCap: true, capIsNew: false }],
      'new-parens': 'warn',
      'newline-per-chained-call': ['warn', { ignoreChainWithDepth: 2 }],
      'no-array-constructor': 'warn',
      'no-bitwise': 'warn',
      'no-continue': 'off',
      'no-inline-comments': 'off',
      'no-lonely-if': 'warn',
      'no-mixed-operators': ['warn', {
        groups: [
          ['&', '|', '^', '~', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||'],
          ['in', 'instanceof']
        ],
        allowSamePrecedence: true
      }],
      'no-mixed-spaces-and-tabs': 'warn',
      'no-multi-assign': 'warn',
      'no-multiple-empty-lines': ['warn', { max: 2, maxEOF: 1, maxBOF: 0 }],
      'no-negated-condition': 'warn',
      'no-nested-ternary': 'warn',
      'no-new-object': 'warn',
      'no-plusplus': 'off',
      'no-restricted-syntax': 'warn',
      'no-tabs': 'warn',
      'no-ternary': 'off',
      'no-trailing-spaces': 'warn',
      'no-underscore-dangle': ['warn', { allow: ['_id', '_index'] }],
      'no-unneeded-ternary': ['warn', { defaultAssignment: false }],
      'no-whitespace-before-property': 'warn',
      'object-curly-newline': ['warn', { consistent: true }],
      'object-curly-spacing': ['warn', 'always'],
      'object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
      'one-var': ['warn', 'never'],
      'one-var-declaration-per-line': 'warn',
      'operator-assignment': ['warn', 'always'],
      'operator-linebreak': ['warn', 'after', { overrides: { '?': 'before', ':': 'before' } }],
      'padded-blocks': ['warn', 'never'],
      'padding-line-between-statements': [
        'warn',
        { blankLine: 'always', prev: '*', next: 'return' },
        { blankLine: 'always', prev: '*', next: 'throw' },
        { blankLine: 'always', prev: ['const', 'let', 'var'], next: '*' },
        { blankLine: 'any', prev: ['const', 'let', 'var'], next: ['const', 'let', 'var'] }
      ],
      'quote-props': ['warn', 'as-needed', { keywords: false, unnecessary: true, numbers: false }],
      'quotes': ['warn', 'single', { avoidEscape: true, allowTemplateLiterals: true }],
      'require-jsdoc': 'off',
      'semi': ['warn', 'always'],
      'semi-spacing': ['warn', { before: false, after: true }],
      'semi-style': ['warn', 'last'],
      'sort-keys': 'off',
      'sort-vars': 'off',
      'space-before-blocks': ['warn', 'always'],
      'space-before-function-paren': ['warn', { anonymous: 'always', named: 'never', asyncArrow: 'always' }],
      'space-in-parens': ['warn', 'never'],
      'space-infix-ops': 'warn',
      'space-unary-ops': ['warn', { words: true, nonwords: false }],
      'spaced-comment': ['warn', 'always', { markers: ['!', '*', '/'] }],
      'switch-colon-spacing': ['warn', { after: true, before: true }],
      'template-curly-spacing': ['warn', 'never'],
      'template-tag-spacing': ['warn', 'never'],
      'unicode-bom': ['warn', 'never'],

      // ES6+
      'arrow-body-style': ['warn', 'as-needed'],
      'arrow-parens': ['warn', 'always'],
      'arrow-spacing': ['warn', { before: true, after: true }],
      'constructor-super': 'warn',
      'generator-star-spacing': ['warn', 'before'],
      'no-class-assign': 'warn',
      'no-confusing-arrow': 'warn',
      'no-const-assign': 'warn',
      'no-dupe-class-members': 'warn',
      'no-duplicate-imports': 'warn',
      'no-new-symbol': 'warn',
      'no-restricted-imports': 'off',
      'no-this-before-super': 'warn',
      'no-useless-computed-key': 'warn',
      'no-useless-constructor': 'warn',
      'no-useless-rename': ['warn', { ignoreDestructuring: false, ignoreImport: false, ignoreExport: false }],
      'no-var': 'warn',
      'object-shorthand': ['warn', 'always'],
      'prefer-arrow-callback': 'warn',
      'prefer-const': 'warn',
      'prefer-destructuring': ['warn', { array: false, object: true }],
      'prefer-numeric-literals': 'warn',
      'prefer-object-spread': 'warn',
      'prefer-reflect': 'off',
      'prefer-rest-params': 'warn',
      'prefer-spread': 'warn',
      'prefer-template': 'warn',
      'require-yield': 'warn',
      'symbol-description': 'warn'
    }
  },

  // HTML files - minimal rules
  {
    files: ['**/*.html'],
    rules: {
      'no-unused-vars': 'off',
      'no-undef': 'off'
    }
  },

  // Config files
  {
    files: ['*.json', '*.toml', '*.yaml', '*.yml'],
    rules: {
      'no-unused-vars': 'off',
      'no-undef': 'off'
    }
  },

  // Test files - relaxed rules
  {
    files: ['**/*.test.js', '**/*.spec.js', '**/__tests__/**', '**/__mocks__/**'],
    rules: {
      'no-unused-expressions': 'off',
      'no-unused-vars': 'off',
      'max-lines-per-function': 'off',
      'max-statements': 'off',
      'max-params': 'off',
      'max-depth': 'off',
      'max-nested-callbacks': 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off'
    }
  }
];